from mcp.server.fastmcp import FastMCP
from settings import Settings
from user_repository import UserRepository
import logging
from settings import Settings
from llm_logger import log_error, log_sql_output

settings = Settings()
logger = logging.getLogger("llm_logger")

MCP_PORT =  settings.MCP_SERVER_PORT
mcp = FastMCP("RBChat", port=MCP_PORT)



@mcp.tool()
def run_sql_query(query: str) -> str:
    """
    Executes a safe, read-only database SELECT query and returns the results.

    Args:
        query: A database language SELECT query generated by the LLM, such as SQL

    Returns:
        A formatted string or JSON of the result rows.
    """
    log_sql_output(query)
    if not query.strip().lower().startswith("select"):
        return "Only SELECT queries are allowed."

    try:
        with UserRepository() as user_repo:
            result = user_repo.run_sql_query(query)
        return str(result)
    except Exception as e:
        log_error(f"Error running SQL query: {e}")
        return f"Query failed: {e}"


if __name__ == "__main__":
    mcp.run(transport="streamable-http")
    # or docker build -t mcp-server .
    # docker run -d -p 7999:7999 --env-file .env --name mcp-server-container mcp-server